"""Shared dataclasses and JSON helpers for reasoning experiments."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Dict, Iterable, List, Mapping, Optional, Sequence

import numpy as np


GridLike = Sequence[Sequence[int]]


def grid_to_list(grid: np.ndarray) -> List[List[int]]:
    return [[int(v) for v in row] for row in np.asarray(grid, dtype=int).tolist()]


def grid_from_list(grid: GridLike) -> np.ndarray:
    return np.asarray(grid, dtype=int)


@dataclass(frozen=True)
class ProgramStep:
    """A single named transformation and its JSON-serializable parameters."""

    name: str
    params: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {"name": self.name, "params": dict(self.params)}

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ProgramStep":
        return cls(name=str(data["name"]), params=dict(data.get("params", {})))

    def short(self) -> str:
        if not self.params:
            return self.name
        param_text = ",".join(f"{k}={self.params[k]}" for k in sorted(self.params))
        return f"{self.name}({param_text})"


Program = List[ProgramStep]


def program_to_dict(program: Iterable[ProgramStep]) -> List[Dict[str, Any]]:
    return [step.to_dict() for step in program]


def program_from_dict(data: Iterable[Mapping[str, Any]]) -> Program:
    return [ProgramStep.from_dict(step) for step in data]


def program_signature(program: Iterable[ProgramStep]) -> str:
    return " -> ".join(step.short() for step in program) or "identity"


@dataclass
class TaskExample:
    """One input-output pair plus generator metadata."""

    input_grid: np.ndarray
    output_grid: np.ndarray
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "input_grid": grid_to_list(self.input_grid),
            "output_grid": grid_to_list(self.output_grid),
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "TaskExample":
        return cls(
            input_grid=grid_from_list(data["input_grid"]),
            output_grid=grid_from_list(data["output_grid"]),
            metadata=dict(data.get("metadata", {})),
        )


@dataclass
class ReasoningTask:
    """An ARC-like task with train/val/test/OOD examples and true latent metadata."""

    task_id: str
    family: str
    program: Program
    examples: Dict[str, List[TaskExample]]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def all_examples(self) -> List[TaskExample]:
        out: List[TaskExample] = []
        for split_examples in self.examples.values():
            out.extend(split_examples)
        return out

    def to_dict(self) -> Dict[str, Any]:
        return {
            "task_id": self.task_id,
            "family": self.family,
            "program": program_to_dict(self.program),
            "examples": {
                split: [example.to_dict() for example in examples]
                for split, examples in self.examples.items()
            },
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "ReasoningTask":
        return cls(
            task_id=str(data["task_id"]),
            family=str(data["family"]),
            program=program_from_dict(data["program"]),
            examples={
                split: [TaskExample.from_dict(example) for example in examples]
                for split, examples in dict(data["examples"]).items()
            },
            metadata=dict(data.get("metadata", {})),
        )


@dataclass
class TaskSuite:
    """A collection of tasks generated by one config."""

    name: str
    tasks: List[ReasoningTask]
    config: Dict[str, Any]
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "name": self.name,
            "tasks": [task.to_dict() for task in self.tasks],
            "config": self.config,
            "metadata": self.metadata,
        }

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> "TaskSuite":
        return cls(
            name=str(data["name"]),
            tasks=[ReasoningTask.from_dict(task) for task in data["tasks"]],
            config=dict(data.get("config", {})),
            metadata=dict(data.get("metadata", {})),
        )


@dataclass
class CandidateResult:
    """A scored candidate hypothesis."""

    program: Program
    train_error: float
    score: float
    diagnostics: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "program": program_to_dict(self.program),
            "program_signature": program_signature(self.program),
            "train_error": float(self.train_error),
            "score": float(self.score),
            "diagnostics": self.diagnostics,
        }


@dataclass
class PredictionResult:
    """Predictions and hypothesis metadata for one task."""

    model_name: str
    task_id: str
    family: str
    predictions: Dict[str, List[np.ndarray]]
    candidate: Optional[CandidateResult]
    diagnostics: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "model_name": self.model_name,
            "task_id": self.task_id,
            "family": self.family,
            "predictions": {
                split: [grid_to_list(grid) for grid in grids]
                for split, grids in self.predictions.items()
            },
            "candidate": None if self.candidate is None else self.candidate.to_dict(),
            "diagnostics": self.diagnostics,
        }

