#!/usr/bin/env python3
"""AUTONOMOUS M1-for-parameters (lever 1): mine LOO fold-divergence traces
cross-task to find WHERE re-derivation fails and WHAT expression forms
would fix it.

Input: outputs/loo_traces/<tid>.json (near-solve records with
residual["loo_divergence"], generated by scripts/generate_loo_traces.py
from the round-9 instrumentation).

For every trace, diff the full-data program against each reinduced fold
program at rule/parameter granularity (same classification as
scripts/blocker_census.py) and aggregate cross-task:

  param_value_diff  <action>.<param>:<op>  — the expression KIND re-derives
                    but its ARGS don't (constants and maps that memorize);
                    a relational spelling for this parameter is the fix
  param_kind_diff   the fold picked a different expression kind — ranking
                    instability or a missing forced spelling
  selector_diff / structure_diff — fold search walked elsewhere entirely

Output: outputs/param_expr_mining.json with
  - divergence_kind histogram (cross-task, task-deduped and instance counts)
  - per dominant kind: task lists + sampled (full_expr, fold_exprs) diffs
  - the verdict block: ranked candidate targets for a new relational
    ExprType, with supporting task counts

This is the M1 residual-mining stage of the parameter loop; the M2/M3
analogue (search expression forms + register under retro-validation)
consumes this report.

Usage: param_expr_miner.py [traces_dir=outputs/loo_traces]
                           [out=outputs/param_expr_mining.json]
"""
import glob
import json
import os
import sys
from collections import Counter, defaultdict

sys.path.insert(0, ".")
from geocat_arc.object_reasoning.trace_mining import classify_divergence

TRACES = sys.argv[1] if len(sys.argv) > 1 else "outputs/loo_traces"
OUT = sys.argv[2] if len(sys.argv) > 2 else "outputs/param_expr_mining.json"


def _rules(prog):
    return (prog or {}).get("rules") or []


def _param_pairs(full_prog, fold_prog):
    """Yield (kind_key, detail) for every parameter-level divergence."""
    fr, gr = _rules(full_prog), _rules(fold_prog)
    if len(fr) != len(gr):
        return
    for rf, rg in zip(fr, gr):
        af = (rf.get("action") or {})
        ag = (rg.get("action") or {})
        if af.get("delta_type") != ag.get("delta_type"):
            return
        pf, pg = af.get("params") or {}, ag.get("params") or {}
        for name in set(pf) | set(pg):
            ef, eg = pf.get(name), pg.get(name)
            if ef == eg or ef is None or eg is None:
                continue
            key = f"{af.get('delta_type')}.{name}"
            yield key, {"full": ef, "fold": eg,
                        "same_kind": ef.get("op") == eg.get("op")}


def main():
    files = sorted(glob.glob(f"{TRACES}/*.json"))
    kind_tasks = defaultdict(set)
    kind_instances = Counter()
    param_targets = defaultdict(lambda: {"tasks": set(), "samples": []})
    n_traced = 0
    for f in files:
        tid = os.path.basename(f)[:-5]
        try:
            rec = json.load(open(f))
        except Exception:
            continue
        div = (rec.get("residual") or {}).get("loo_divergence") or []
        if not div:
            continue
        n_traced += 1
        full_prog = rec.get("program_partial")
        for t in div:
            for k in classify_divergence(full_prog, t):
                base = k.split(":")[0]
                kind_tasks[base].add(tid)
                kind_instances[k] += 1
            for key, detail in _param_pairs(full_prog,
                                            t.get("fold_program")):
                tgt = param_targets[key]
                tgt["tasks"].add(tid)
                if len(tgt["samples"]) < 6:
                    tgt["samples"].append({"task": tid, **detail})

    verdict = sorted(
        ({"target": k, "n_tasks": len(v["tasks"]),
          "tasks": sorted(v["tasks"]), "samples": v["samples"]}
         for k, v in param_targets.items()),
        key=lambda e: -e["n_tasks"])
    report = {
        "traces": n_traced,
        "divergence_kind_tasks": {k: len(v) for k, v in
                                  sorted(kind_tasks.items(),
                                         key=lambda kv: -len(kv[1]))},
        "divergence_instances_top": dict(kind_instances.most_common(30)),
        "param_targets_ranked": verdict,
    }
    json.dump(report, open(OUT, "w"), indent=1)
    print(f"traces analyzed: {n_traced}")
    print("kind (distinct tasks):", report["divergence_kind_tasks"])
    for e in verdict[:10]:
        print(f"  TARGET {e['target']}: {e['n_tasks']} tasks")
    print(f"-> {OUT}")


if __name__ == "__main__":
    main()
