"""v1.9 supplementary development measurement: which K*-4 clause carries the
false acceptances of the reduced-demonstration control (DEVELOPMENT ONLY).

Every trial of `v19_falseaccept_reduced_dev.py` is regenerated by the same
deterministic code (production names checked against its rows) and run on
the four training pairs S under K*' with the fitting clause only and with
the ranking clause only. Rows: outputs/tti/v19_clause_safety_dev_rows.jsonl.

  worker <wid> | reset_claims | analyze
"""
import collections
import json
import os
import sys
import time

HERE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, HERE)
sys.path.insert(0, os.path.join(HERE, "scripts"))

from cora_arc2026 import v17_compiler as X                        # noqa: E402
import v19_repair_dev as RD                                       # noqa: E402
import v19_falseaccept_reduced_dev as FR                          # noqa: E402

R = RD.R
ROWS = os.path.join(RD.OUT, "v19_clause_safety_dev_rows.jsonl")
REPORT = os.path.join(RD.OUT, "v19_clause_safety_dev_report.json")
CLAIMS = os.path.join(RD.LOG, "clause_safety_claims.json")


def process(task, ref):
    train = [RD.ungrid(p) for p in task["train"]]
    held = RD.ungrid(task["held"])
    S, E = train[:FR.K], train[FR.K:] + [held]
    tl, _pool, _cls = FR.trials(S, E)
    names = [pw["name"] for _k, _s, pw in tl]
    row = {"index": task["index"], "names_match": names == [t["production"] for t in ref["trials"]],
           "trials": []}
    for kind, source, pw in tl:
        out = {"kind": kind, "source": source, "production": pw["name"]}
        for clause in ("fit", "rank"):
            run = R.run_reasoner(S, (pw,), clauses=(clause,))
            out[clause] = {"accepted": run["accepted"],
                           "right_on_E": FR.engine_on(run, E) if run["accepted"] else None,
                           "uses": bool(run["accepted"] and X.uses_extension(run["program"], pw))}
        row["trials"].append(out)
    return row


def items():
    ref = {r["index"]: r for r in RD.read_rows(FR.ROWS) if r.get("status") != "RUN_ERROR"}
    return [(t, ref[t["index"]]) for t, _d in RD.tasks() if t["index"] in ref and ref[t["index"]]["trials"]]


def worker(wid):
    its = items()
    while True:
        j = RD.claim(CLAIMS, len(its))
        if j is None:
            break
        task, ref = its[j]
        try:
            row = process(task, ref)
        except Exception as exc:                              # noqa: BLE001
            import traceback
            row = {"index": task["index"], "status": "RUN_ERROR", "error": type(exc).__name__,
                   "trace": traceback.format_exc()[-2000:]}
        row["worker"] = wid
        RD.append(ROWS, row)
        print(f"{time.strftime('%H:%M:%S')} w{wid} task {row['index']}", flush=True)


def analyze():
    ref = {r["index"]: r for r in RD.read_rows(FR.ROWS) if r.get("status") != "RUN_ERROR"}
    rows = [r for r in RD.read_rows(ROWS) if r.get("status") != "RUN_ERROR"]
    table = collections.Counter()
    for r in rows:
        for t, b in zip(r["trials"], ref[r["index"]]["trials"]):
            for side, res in (("old", b["old"]), ("both", b["new"]), ("fit", t["fit"]), ("rank", t["rank"])):
                ok = res["accepted"] and res["right_on_E"]
                bad = res["accepted"] and not res["right_on_E"]
                table[(t["kind"], side, "true_accept" if ok else "false_accept" if bad else "rejected")] += 1
    out = {"tasks": len(rows), "names_match_all": all(r["names_match"] for r in rows),
           "errors": len(RD.read_rows(ROWS)) - len(rows),
           "table": {f"{k[0]}|{k[1]}|{k[2]}": v for k, v in sorted(table.items())}}
    json.dump(out, open(REPORT, "w"), indent=1)
    print(json.dumps(out, indent=1))


if __name__ == "__main__":
    cmd = sys.argv[1]
    if cmd == "worker":
        worker(int(sys.argv[2]))
    elif cmd == "reset_claims":
        its = items()
        done = {r["index"] for r in RD.read_rows(ROWS)}
        json.dump([i for i, (t, _r) in enumerate(its) if t["index"] in done], open(CLAIMS, "w"))
    elif cmd == "analyze":
        analyze()
